//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "api_key_usage_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id:          String,
    #[sea_orm(column_type = "Text")]
    pub api_key_id:  String,
    pub endpoint:    String,
    pub method:      String,
    pub ip_address:  Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent:  Option<String>,
    pub status_code: i16,
    pub created_at:  DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "api_key_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub api_keys:    HasOne<super::api_keys::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
