//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "refresh_tokens")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id:            i32,
    pub user_id:       Uuid,
    #[sea_orm(column_type = "Text", unique)]
    #[serde(skip_serializing)]
    pub token_hash:    String,
    pub expires_at:    DateTimeWithTimeZone,
    pub revoked_at:    Option<DateTimeWithTimeZone>,
    pub created_at:    DateTimeWithTimeZone,
    pub updated_at:    DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub user_sessions: HasMany<super::user_sessions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users:         HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
