//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id:          Uuid,
    pub name:        String,
    #[sea_orm(unique)]
    pub slug:        String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub permissions: Json,
    pub is_system:   bool,
    pub created_at:  DateTime,
    pub updated_at:  DateTime,
    #[sea_orm(has_many)]
    pub user_roles:  HasMany<super::user_roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
