//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role_scope_type")]
pub enum RoleScopeType {
    #[sea_orm(string_value = "global")]
    Global,
    #[sea_orm(string_value = "team")]
    Team,
    #[sea_orm(string_value = "asset")]
    Asset,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "team_member_role")]
pub enum TeamMemberRole {
    #[sea_orm(string_value = "owner")]
    Owner,
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "member")]
    Member,
    #[sea_orm(string_value = "viewer")]
    Viewer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_status")]
pub enum UserStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "suspended")]
    Suspended,
    #[sea_orm(string_value = "pending_verification")]
    PendingVerification,
}

// ===== START CUSTOM EDIT: display_for_role_scope_type =====
impl std::fmt::Display for RoleScopeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RoleScopeType::Global => write!(f, "global"),
            RoleScopeType::Team => write!(f, "team"),
            RoleScopeType::Asset => write!(f, "asset"),
        }
    }
}
// ===== END CUSTOM EDIT: display_for_role_scope_type =====

// ===== START CUSTOM EDIT: display_for_team_member_role =====
impl std::fmt::Display for TeamMemberRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TeamMemberRole::Owner => write!(f, "owner"),
            TeamMemberRole::Admin => write!(f, "admin"),
            TeamMemberRole::Member => write!(f, "member"),
            TeamMemberRole::Viewer => write!(f, "viewer"),
        }
    }
}
// ===== END CUSTOM EDIT: display_for_team_member_role =====

// ===== START CUSTOM EDIT: display_for_user_status =====
impl std::fmt::Display for UserStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            UserStatus::Active => write!(f, "active"),
            UserStatus::Inactive => write!(f, "inactive"),
            UserStatus::Suspended => write!(f, "suspended"),
            UserStatus::PendingVerification => write!(f, "pending_verification"),
        }
    }
}
// ===== END CUSTOM EDIT: display_for_user_status =====
