//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "system_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id:          String,
    #[sea_orm(unique)]
    pub key:         String,
    pub value:       String,
    pub description: Option<String>,
    pub updated_at:  DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
