//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "teams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id:             Uuid,
    pub name:           String,
    #[sea_orm(unique)]
    pub slug:           String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description:    Option<String>,
    pub parent_team_id: Option<Uuid>,
    pub manager_id:     Uuid,
    pub created_at:     DateTime,
    pub updated_at:     DateTime,
    pub deleted_at:     Option<DateTime>,
    #[sea_orm(has_many)]
    pub team_members:   HasMany<super::team_members::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_team_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub teams:          HasOne<Entity>,
    #[sea_orm(
        belongs_to,
        from = "manager_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub users:          HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
