//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::TeamMemberRole;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "team_members")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id:         String,
    #[sea_orm(unique_key = "idx_team_members_team_user_unique")]
    pub team_id:    String,
    #[sea_orm(unique_key = "idx_team_members_team_user_unique")]
    pub user_id:    String,
    pub role:       TeamMemberRole,
    pub joined_at:  DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub teams:      HasOne<super::teams::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users:      HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
