//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::RoleScopeType;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id:          Uuid,
    #[sea_orm(unique_key = "idx_user_roles_user_role_scope_unique")]
    pub user_id:     Uuid,
    #[sea_orm(unique_key = "idx_user_roles_user_role_scope_unique")]
    pub role_id:     Uuid,
    #[sea_orm(unique_key = "idx_user_roles_user_role_scope_unique")]
    pub scope_type:  RoleScopeType,
    #[sea_orm(unique_key = "idx_user_roles_user_role_scope_unique")]
    pub scope_id:    Option<Uuid>,
    pub expires_at:  Option<DateTime>,
    pub assigned_at: DateTime,
    pub created_at:  DateTime,
    pub updated_at:  DateTime,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub roles:       HasOne<super::roles::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users:       HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
