//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id:               Uuid,
    pub user_id:          Uuid,
    pub refresh_token_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_agent:       Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip_address:       Option<String>,
    pub created_at:       DateTimeWithTimeZone,
    pub last_used_at:     DateTimeWithTimeZone,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_at:       Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "refresh_token_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub refresh_tokens:   HasOne<super::refresh_tokens::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users:            HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
